image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE: registry.gitlab.com/v.halionka/pyraken
  IMAGE_LABEL: pyraken

build:
  stage: build
  before_script:
    - docker info
  only:
    - develop
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && git -C $PROJECT_DIR pull https://$CI_USERNAME:$CI_PASSWORD@$GIT_REPO develop"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && cd $PROJECT_DIR && docker build --label $IMAGE_LABEL -t $IMAGE ."
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && cd $PROJECT_DIR && docker login registry.gitlab.com -u $CI_USERNAME -p $CI_PASSWORD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && cd $PROJECT_DIR && docker push $IMAGE"

deploy:
  stage: deploy
  before_script:
    - docker info
  only:
    - develop
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && cd $PROJECT_DIR && docker-compose up -d"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd .. && docker image prune -a -f --filter 'label=$IMAGE_LABEL' && docker volume prune -f"
