image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE: registry.gitlab.com/v.halionka/pyraken .

build:
  stage: build
  before_script:
    - echo "uname -a"
    - docker info
    - docker login registry.gitlab.com -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD
  only:
    - master
  script:
    - docker build -t $IMAGE:latest .
    - docker push $IMAGE:latest

deploy:
  stage: deploy
  before_script:
    - echo "uname -a"
    - docker info
    - docker login registry.gitlab.com -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD
    - apk update
    - apk upgrade
    - apk add --no-cache docker-compose
  only:
    - master
  script:
    - docker-compose pull && docker-compose up -d