version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyraken-django
    ports:
      - "8000:8000"
    volumes:
      - .:/pyraken
    depends_on:
      - db
      - rabbitmq
      - redis
    restart: always
    environment:
      - SECRET_KEY_=${SECRET_KEY}
      - ALLOWED_HOSTS_=${ALLOWED_HOSTS}
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - RABBIT_MQ_NAME_=${RABBIT_MQ_NAME}
      - RABBIT_MQ_PASS_=${RABBIT_MQ_PASS}
      - RABBIT_MQ_IP_=${RABBIT_MQ_IP}
      - RABBIT_MQ_PORT_=${RABBIT_MQ_PORT}
    command: ./start_django.sh

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: pyraken-db
    ports:
      - '5432:5432'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pyraken-rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    restart: always

  redis:
    image: redis:latest
    container_name: pyraken-redis
    ports:
      - "6379:6379"
    restart: always
