version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyraken-django
    ports:
      - "8000:8000"
    volumes:
      - .:/pyraken
    depends_on:
      - db
      - rabbitmq
      - redis
    restart: always
    command: ./start_django.sh

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: pyraken-db
    ports:
      - '5432:5432'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pyraken-rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_NAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}

  redis:
    image: redis:latest
    container_name: pyraken-redis
    ports:
      - "6379:6379"
    restart: always
    command: >
      --requirepass ${REDIS_PASS}
