# Generated by Django 3.1.3 on 2020-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201121_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='even_number',
        ),
        migrations.AddField(
            model_name='flag',
            name='borders_symbol',
            field=models.CharField(default='#', max_length=1),
        ),
        migrations.AddField(
            model_name='flag',
            name='free_space_symbol',
            field=models.CharField(default='&nbsp;&nbsp;', max_length=12),
        ),
        migrations.AddField(
            model_name='flag',
            name='inner_circle_symbol',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='flag',
            name='outer_circle_symbol',
            field=models.CharField(default='*', max_length=1),
        ),
    ]
