# Generated by Django 3.1.3 on 2020-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201121_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='is_default_object',
            field=models.BooleanField(default=False),
        ),
    ]
